[workspace]

members = [
    "fuzzcheck_arg_parser",
    "cargo-fuzzcheck",
    "fuzzcheck",
    "fuzzcheck_mutators",
    "fuzzcheck_serializer",
    "fuzzcheck_mutator_trait"
]

exclude = [
    "usage_tests"
]
