[workspace]

members = [
    "fuzzcheck_arg_parser",
    "cargo-fuzzcheck",
    "fuzzcheck",
    "fuzzcheck_mutators",
    "fuzzcheck_serializer",
    "nix_subset"
]

exclude = [
    "usage_tests"
]

[profile.release.cargo-fuzzcheck]
opt-level = 0