[workspace]

members = [
    "fuzzcheck_common",
    "cargo-fuzzcheck",
    "fuzzcheck",
    "fuzzcheck_mutators",
    "fuzzcheck_mutators_derive",
    "fuzzcheck_serializer",
    "fuzzcheck_traits",
]

exclude = [
    "usage_tests",
]
