[workspace]

members = [
    "fuzzcheck_arg_parser",
    "cargo-fuzzcheck",
    "fuzzcheck",
    "fuzzcheck_mutators",
    "fuzzcheck_mutators_derive",
    "fuzzcheck_serializer",
    "fuzzcheck_traits"
]

exclude = [
    "usage_tests"
]
