[package]
name = "fuzzcheck"
version = "0.1.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"
description = "A coverage-guided, structure-aware fuzzing engine for Rust functions"
repository = "https://git.sr.ht/~loic/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["fuzzing", "test"]
categories = ["development-tools"]

[dependencies.getopts]
version = "0.2"

[dependencies.ahash]
version = "0.3"
default_features = false
features = ["std"]

[dependencies.rand]
version = "0.7"
default_features = false
features = ["small_rng"]

[dependencies.fuzzcheck_nix_subset]
path = "../fuzzcheck_nix_subset"
version = "0.1.0"

[dependencies.fuzzcheck_arg_parser]
path = "../fuzzcheck_arg_parser"
version = "0.1.0"

[lib]
name = "fuzzcheck"