[package]
name = "fuzzcheck"
version = "0.4.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"
description = "A coverage-guided, structure-aware fuzzing engine for Rust functions"
repository = "https://git.sr.ht/~loic/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["fuzzing", "test"]
categories = ["development-tools"]

[dependencies.packed_simd]
version = "0.3.4"
package = "packed_simd_2"

[dependencies.base64]
version = "0.13"

[dependencies.json]
version = "0.12"

[dependencies.decent-serde-json-alternative]
path = "../../decent-serde-json-alternative"
version = "0.2"
features = ["derive"]

[dependencies.getopts]
version = "0.2"

[dependencies.fastrand]
version = "1.0"

[dependencies.bitflags]
version = "1.1"

[dependencies.cfg-if]
version = "0.1.10"

[dependencies.libc]
default_features = false
version = "0.2"

[dependencies.fuzzcheck_common]
path = "../fuzzcheck_common"
version = "0.4.0"

[target.'cfg(not(fuzzcheck))'.dependencies.fuzzcheck_traits]
path = "../fuzzcheck_traits"
version = "0.4.0"

[lib]
name = "fuzzcheck"
