[package]
name = "fuzzcheck"
version = "0.6.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"
description = "A coverage-guided, structure-aware fuzzing engine for Rust functions"
repository = "https://git.sr.ht/~loic/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["fuzzing", "test"]
categories = ["development-tools"]
links = "fuzzcheck_traits"

[features]
default = ["compile-fuzzcheck-traits"]
ui = ["base64", "json", "decent-serde-json-alternative", "fuzzcheck_common/ui"]
compile-fuzzcheck-traits = ["fuzzcheck_traits"]

[dependencies.base64]
version = "*"
optional = true

[dependencies.json]
version = "*"
optional = true

[dependencies.decent-serde-json-alternative]
version = "0.4.0"
optional = true

[dependencies.getopts]
version = "*"

[dependencies.fastrand]
version = "*"

[dependencies.bitflags]
version = "*"

[dependencies.cfg-if]
version = "*"

[dependencies.libc]
default_features = false
version = "*"

[dependencies.fuzzcheck_common]
path = "../fuzzcheck_common"
version = "0.6.0"

# [target.'cfg(not(fuzzcheck))'.dependencies.fuzzcheck_traits]
# path = "../fuzzcheck_traits"
# version = "0.6.0"
[dependencies.fuzzcheck_traits]
path = "../fuzzcheck_traits"
version = "0.6.0"
optional = true

[dependencies.backtrace]
version = "*"

[lib]
name = "fuzzcheck"
