[package]
name = "fuzzcheck"
version = "0.1.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"
description = "A coverage-guided, structure-aware fuzzing engine for Rust functions"
repository = "https://git.sr.ht/~loic/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["fuzzing", "test"]
categories = ["development-tools"]

[dependencies]
rand = { version = "0.7", features = ["small_rng"] }
rand_distr = "0.2"
libc = "0.2"
lazy_static = "1.4"
ahash = { version = "0.2", default_features = false, features = ["std"] }
getopts = "0.2"
fuzzcheck_arg_parser = { path = "../fuzzcheck_arg_parser" }

[lib]
name = "fuzzcheck"