[package]
name = "fuzzcheck"
version = "0.2.1"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"
description = "A coverage-guided, structure-aware fuzzing engine for Rust functions"
repository = "https://git.sr.ht/~loic/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["fuzzing", "test"]
categories = ["development-tools"]

[dependencies.getopts]
version = "0.2"

[dependencies.fastrand]
version = "1.0"

[dependencies.bitflags]
version = "1.1"

[dependencies.cfg-if]
version = "0.1.10"

[dependencies.libc]
default_features = false
version = "0.2"

[dependencies.fuzzcheck_arg_parser]
path = "../fuzzcheck_arg_parser"
version = "0.2.1"

# this is conditional on not being compiled as part of a fuzz test because
# in that case, the fuzzcheck_mutator_trait crate is linked manually
# via link-search in the build script, so cargo should not try to fetch
# any version of it
[target.'cfg(not(fuzzcheck_fuzz_target))'.dependencies.fuzzcheck_mutator_trait]
path = "../fuzzcheck_mutator_trait"
version = "0.2.1"

[lib]
name = "fuzzcheck"