[package]
name = "fuzzcheck"
version = "0.2.1"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"
description = "A coverage-guided, structure-aware fuzzing engine for Rust functions"
repository = "https://git.sr.ht/~loic/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["fuzzing", "test"]
categories = ["development-tools"]

[dependencies.getopts]
version = "0.2"

[dependencies.fastrand]
version = "1.0"

[dependencies.bitflags]
version = "1.1"

[dependencies.cfg-if]
version = "0.1.10"

[dependencies.libc]
default_features = false
version = "0.2"

[dependencies.fuzzcheck_arg_parser]
path = "../fuzzcheck_arg_parser"
version = "0.2.1"

[target.'cfg(not(fuzzcheck))'.dependencies.fuzzcheck_traits]
path = "../fuzzcheck_traits"
version = "0.2.1"

[lib]
name = "fuzzcheck"
