[package]
name = "fuzzcheck"
version = "0.1.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"
description = "A coverage-guided, structure-aware fuzzing engine for Rust functions"
repository = "https://git.sr.ht/~loic/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["fuzzing", "test"]
categories = ["development-tools"]

[dependencies]
#rand_distr = "0.2"
nix_subset = { path = "../nix_subset" }
ahash = { version = "0.3", default_features = false, features = ["std"] }
getopts = "0.2"
fuzzcheck_arg_parser = { path = "../fuzzcheck_arg_parser" }

[dependencies.rand]
version = "0.7"
default_features = false
features = ["small_rng"]

[lib]
name = "fuzzcheck"