[package]
name = "fuzzcheck"
version = "0.8.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2021"
description = "A modular, structure-aware, and feedback-driven fuzzing engine for Rust functions"
homepage = "https://fuzzcheck.neocities.org"
repository = "https://github.com/loiclec/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["property", "fuzzer", "fuzzing", "test", "testing"]
categories = ["development-tools::testing"]

[build-dependencies]
cc = "1"

[features]

[dependencies]
getopts = "0.2"
fastrand = "1"
bitflags = "1"
cfg-if = "1"
libc = { version = "0.2", default_features = false  }

md5 = "0.7"
object = { version = "0.27", default_features = false, features = ["read"] }
flate2 = { version = "1", default_features = false, features = ["zlib"] }

fuzzcheck_common = { path = "../fuzzcheck_common", version = "0.8.0" }

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

fuzzcheck_mutators_derive = {path = "../fuzzcheck_mutators_derive", version = "0.8.0" }

ahash = "0.7"

regex-syntax = "0.6"
nu-ansi-term = "0.39"

[lib]
name = "fuzzcheck"
