[package]
name = "fuzzcheck"
version = "0.6.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"
description = "A coverage-guided, structure-aware fuzzing engine for Rust functions"
repository = "https://git.sr.ht/~loic/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["fuzzing", "test"]
categories = ["development-tools"]
links = "fuzzcheck_traits"

[build-dependencies]
cc = "*"

[features]
default = ["mutators", "serde_json_serializer"]
mutators = ["fuzzcheck_mutators"]
serde_json_serializer = ["fuzzcheck_serializer/serde-json"]
serde_json_alternative_serializer = ["fuzzcheck_serializer/serde-json-alternative"]

ui = ["base64", "json", "decent-serde-json-alternative", "fuzzcheck_common/ui"]

[dependencies]
getopts = "0.2"
fastrand = "1"
bitflags = "1"
cfg-if = "1"
libc = { version = "0.2", default_features = false  }

md5 = "0.7"
object = { version = "0.26", default_features = false, features = ["read"] }

fuzzcheck_common = { path = "../fuzzcheck_common", version = "0.6.0" }
fuzzcheck_traits = { path = "../fuzzcheck_traits", version = "0.6.0" }
fuzzcheck_mutators = { path = "../fuzzcheck_mutators", version = "0.6.0", optional = true }
fuzzcheck_serializer = { path = "../fuzzcheck_serializer", version = "0.6.0", optional = true }

base64 = { version = "0.13", optional = true }
json = { version = "0.12", optional = true }
decent-serde-json-alternative  = { version = "0.4.0", optional = true }

[lib]
name = "fuzzcheck"
