[package]
name = "cargo-fuzzcheck"
version = "0.3.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"
description = "Command line tool to use fuzzcheck-rs"
repository = "https://git.sr.ht/~loic/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["fuzzing", "test"]
categories = ["development-tools"]

[dependencies]
getopts = "0.2"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.toml]
version = "0.5"
features = ["preserve_order"]

[dependencies.fuzzcheck_arg_parser]
path = "../fuzzcheck_arg_parser"
version = "0.3.0"

[[bin]]
name = "cargo-fuzzcheck"
path = "src/main.rs"
