[package]
name = "cargo-fuzzcheck"
version = "0.4.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"
description = "Command line tool to use fuzzcheck-rs"
repository = "https://git.sr.ht/~loic/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["fuzzing", "test"]
categories = ["development-tools"]

[dependencies]
getopts = "0.2"
# tui = "0.13.0"
# termion = "1.5"
# json = "0.12"

[dependencies.decent-toml-rs-alternative]
path = "../../decent-toml-rs-alternative"
# git = "https://git.sr.ht/~loic/decent-toml-rs-alternative"

# [dependencies.decent-serde-json-alternative]
# git = "https://git.sr.ht/~loic/decent-serde-json-alternative"

# [dependencies.decent-serde-json-derive-alternative]
# git = "https://git.sr.ht/~loic/decent-serde-json-derive-alternative"

[dependencies.decent-serde-toml-derive-alternative]
git = "https://git.sr.ht/~loic/decent-serde-toml-derive-alternative"


[dependencies.fuzzcheck_arg_parser]
path = "../fuzzcheck_arg_parser"
version = "0.4.0"

[[bin]]
name = "cargo-fuzzcheck"
path = "src/main.rs"