[package]
name = "cargo-fuzzcheck"
version = "0.4.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"
description = "Command line tool to use fuzzcheck-rs"
repository = "https://git.sr.ht/~loic/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["fuzzing", "test"]
categories = ["development-tools"]

[dependencies]
getopts = "0.2"
tui = "0.14.0"
unicode-width = "0.1"
termion = "1.5"
json = "0.12"
libc = "0.2"

[dependencies.decent-toml-rs-alternative]
path = "../../decent-toml-rs-alternative"
version = "0.1"
features = ["derive"]

[dependencies.decent-serde-json-alternative]
path = "../../decent-serde-json-alternative"
version = "0.2"
features = ["derive"]

[dependencies.fuzzcheck_common]
path = "../fuzzcheck_common"
version = "0.4.0"

[[bin]]
name = "cargo-fuzzcheck"
path = "src/main.rs"

[package.decent-toml-rs-alternative]