[package]
name = "cargo-fuzzcheck"
version = "0.5.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"
description = "Command line tool to use fuzzcheck-rs"
repository = "https://git.sr.ht/~loic/fuzzcheck-rs"
readme = "README.md"
license = "MIT"
keywords = ["fuzzing", "test"]
categories = ["development-tools"]

[features]
ui = ["tui", "termion", "unicode-width", "json", "decent-serde-json-alternative", "fuzzcheck_common/ui"]

[dependencies]
getopts = "0.2"
tui = { version = "0.14.0", optional = true }
unicode-width = { version = "0.1", optional = true }
termion = { version = "1.5", optional = true }
json = { version = "0.12", optional = true }
libc = { version = "0.2", optional = true }

[dependencies.decent-toml-rs-alternative]
version = "0.3.0"
features = ["derive"]

[dependencies.decent-serde-json-alternative]
version = "0.4.0"
optional = true

[dependencies.fuzzcheck_common]
path = "../fuzzcheck_common"
version = "0.6.0"

[[bin]]
name = "cargo-fuzzcheck"
path = "src/main.rs"