[package]
name = "fuzzcheck_common"
version = "0.4.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"

[dependencies.json]
version = "0.12"

[dependencies.decent-serde-json-alternative]
path = "/Users/loiclecrenier/Documents/Programming/rust/decent-serde-json-alternative"
version = "0.1"
features = ["derive"]

[lib]
name = "fuzzcheck_common"