[package]
name = "fuzzcheck_common"
version = "0.4.0"
authors = ["Loïc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
ui = ["json", "decent-serde-json-alternative"]

[dependencies]
getopts = "0.2"

[dependencies.json]
version = "0.12"
optional = true

[dependencies.decent-serde-json-alternative]
version = "0.3.0"
optional = true

[lib]
name = "fuzzcheck_common"